import { ColorPalette, FontCollection, TypographyTree, TypographyLevel, AIRecommendation } from '../types';

export function getDefaultTypographyTree(fontFamily: string): TypographyTree {
  const f = fontFamily;
  return {
    displayXl: { fontSize: '48px', lineHeight: '1.1', fontWeight: '900', letterSpacing: '-0.03em', fontFamily: f },
    displayL: { fontSize: '40px', lineHeight: '1.15', fontWeight: '800', letterSpacing: '-0.02em', fontFamily: f },
    displayM: { fontSize: '32px', lineHeight: '1.2', fontWeight: '800', letterSpacing: '-0.015em', fontFamily: f },
    headingXl: { fontSize: '24px', lineHeight: '1.25', fontWeight: '700', letterSpacing: '-0.01em', fontFamily: f },
    headingL: { fontSize: '20px', lineHeight: '1.3', fontWeight: '700', letterSpacing: '-0.005em', fontFamily: f },
    headingM: { fontSize: '18px', lineHeight: '1.35', fontWeight: '600', letterSpacing: '0', fontFamily: f },
    headingS: { fontSize: '16px', lineHeight: '1.4', fontWeight: '600', letterSpacing: '0', fontFamily: f },
    bodyLarge: { fontSize: '16px', lineHeight: '1.5', fontWeight: '400', letterSpacing: '0', fontFamily: f },
    bodyMedium: { fontSize: '14px', lineHeight: '1.6', fontWeight: '400', letterSpacing: '0', fontFamily: f },
    bodySmall: { fontSize: '12px', lineHeight: '1.6', fontWeight: '400', letterSpacing: '0.01em', fontFamily: f },
    caption: { fontSize: '11px', lineHeight: '1.5', fontWeight: '500', letterSpacing: '0.02em', fontFamily: f },
    label: { fontSize: '11px', lineHeight: '1.4', fontWeight: '600', letterSpacing: '0.05em', fontFamily: f, textTransform: 'uppercase' },
    button: { fontSize: '13px', lineHeight: '1', fontWeight: '600', letterSpacing: '0.02em', fontFamily: f },
    tooltip: { fontSize: '11px', lineHeight: '1.3', fontWeight: '500', letterSpacing: '0', fontFamily: f },
    navigation: { fontSize: '13px', lineHeight: '1.4', fontWeight: '600', letterSpacing: '0', fontFamily: f },
    sidebar: { fontSize: '13px', lineHeight: '1.5', fontWeight: '500', letterSpacing: '0', fontFamily: f },
    chart: { fontSize: '11px', lineHeight: '1', fontWeight: '400', letterSpacing: '0', fontFamily: 'JetBrains Mono, monospace' },
    notification: { fontSize: '12px', lineHeight: '1.4', fontWeight: '500', letterSpacing: '0', fontFamily: f },
    code: { fontSize: '12px', lineHeight: '1.5', fontWeight: '400', letterSpacing: '0', fontFamily: 'JetBrains Mono, monospace' }
  };
}

export const BUILT_IN_FONTS: FontCollection[] = [
  { id: 'font_inter', name: 'Inter', family: 'Inter, system-ui, sans-serif', weights: ['300', '400', '500', '600', '700', '800', '900'], styles: ['normal', 'italic'], isMonospace: false, isFavorite: true, isInstalled: true, isEnabled: true, isCustom: false, license: 'OFL', characterSupport: 'Latin, Greek, Cyrillic', languageSupport: ['TR', 'EN', 'DE', 'FR', 'ES'] },
  { id: 'font_roboto', name: 'Roboto', family: 'Roboto, sans-serif', weights: ['100', '300', '400', '500', '700', '900'], styles: ['normal', 'italic'], isMonospace: false, isFavorite: false, isInstalled: true, isEnabled: true, isCustom: false, license: 'Apache 2.0', characterSupport: 'Latin, Cyrillic, Hebrew', languageSupport: ['TR', 'EN', 'DE', 'RU', 'HE'] },
  { id: 'font_sf_pro', name: 'SF Pro', family: '-apple-system, BlinkMacSystemFont, "Segoe UI", Roboto, sans-serif', weights: ['200', '300', '400', '500', '600', '700', '800'], styles: ['normal', 'italic'], isMonospace: false, isFavorite: true, isInstalled: true, isEnabled: true, isCustom: false, license: 'Proprietary Apple', characterSupport: 'Latin', languageSupport: ['EN', 'DE', 'FR'] },
  { id: 'font_geist', name: 'Geist Sans', family: '"Geist Sans", system-ui, sans-serif', weights: ['100', '200', '300', '400', '500', '600', '700', '800', '900'], styles: ['normal'], isMonospace: false, isFavorite: true, isInstalled: true, isEnabled: true, isCustom: false, license: 'OFL', characterSupport: 'Latin', languageSupport: ['TR', 'EN', 'DE'] },
  { id: 'font_manrope', name: 'Manrope', family: 'Manrope, sans-serif', weights: ['200', '300', '400', '500', '600', '700', '800'], styles: ['normal'], isMonospace: false, isFavorite: false, isInstalled: true, isEnabled: true, isCustom: false, license: 'OFL', characterSupport: 'Latin, Cyrillic', languageSupport: ['TR', 'EN', 'DE', 'RU'] },
  { id: 'font_poppins', name: 'Poppins', family: 'Poppins, sans-serif', weights: ['100', '200', '300', '400', '500', '600', '700', '800', '900'], styles: ['normal', 'italic'], isMonospace: false, isFavorite: false, isInstalled: true, isEnabled: true, isCustom: false, license: 'OFL', characterSupport: 'Latin, Devnagari', languageSupport: ['TR', 'EN', 'HI'] },
  { id: 'font_dm_sans', name: 'DM Sans', family: '"DM Sans", sans-serif', weights: ['100', '200', '300', '400', '500', '600', '700', '800', '900'], styles: ['normal', 'italic'], isMonospace: false, isFavorite: false, isInstalled: true, isEnabled: true, isCustom: false, license: 'OFL', characterSupport: 'Latin', languageSupport: ['TR', 'EN', 'DE'] },
  { id: 'font_outfit', name: 'Outfit', family: 'Outfit, sans-serif', weights: ['100', '200', '300', '400', '500', '600', '700', '800', '900'], styles: ['normal'], isMonospace: false, isFavorite: true, isInstalled: true, isEnabled: true, isCustom: false, license: 'OFL', characterSupport: 'Latin', languageSupport: ['TR', 'EN', 'DE'] },
  { id: 'font_plus_jakarta', name: 'Plus Jakarta Sans', family: '"Plus Jakarta Sans", sans-serif', weights: ['200', '300', '400', '500', '600', '700', '800'], styles: ['normal', 'italic'], isMonospace: false, isFavorite: true, isInstalled: true, isEnabled: true, isCustom: false, license: 'OFL', characterSupport: 'Latin', languageSupport: ['TR', 'EN', 'ID'] },
  { id: 'font_ibm_plex', name: 'IBM Plex Sans', family: '"IBM Plex Sans", sans-serif', weights: ['100', '200', '300', '400', '500', '600', '700'], styles: ['normal', 'italic'], isMonospace: false, isFavorite: false, isInstalled: true, isEnabled: true, isCustom: false, license: 'OFL', characterSupport: 'Latin, Cyrillic', languageSupport: ['TR', 'EN', 'DE', 'RU'] },
  { id: 'font_source_sans', name: 'Source Sans 3', family: '"Source Sans 3", sans-serif', weights: ['200', '300', '400', '500', '600', '700', '800', '900'], styles: ['normal', 'italic'], isMonospace: false, isFavorite: false, isInstalled: true, isEnabled: true, isCustom: false, license: 'OFL', characterSupport: 'Latin, Greek, Cyrillic', languageSupport: ['TR', 'EN', 'EL'] },
  { id: 'font_open_sans', name: 'Open Sans', family: '"Open Sans", sans-serif', weights: ['300', '400', '500', '600', '700', '800'], styles: ['normal', 'italic'], isMonospace: false, isFavorite: false, isInstalled: true, isEnabled: true, isCustom: false, license: 'OFL', characterSupport: 'Latin, Greek', languageSupport: ['TR', 'EN', 'GR'] },
  { id: 'font_montserrat', name: 'Montserrat', family: 'Montserrat, sans-serif', weights: ['100', '200', '300', '400', '500', '600', '700', '800', '900'], styles: ['normal', 'italic'], isMonospace: false, isFavorite: false, isInstalled: true, isEnabled: true, isCustom: false, license: 'OFL', characterSupport: 'Latin, Cyrillic', languageSupport: ['TR', 'EN', 'RU'] },
  { id: 'font_space_grotesk', name: 'Space Grotesk', family: '"Space Grotesk", sans-serif', weights: ['300', '400', '500', '600', '700'], styles: ['normal'], isMonospace: false, isFavorite: true, isInstalled: true, isEnabled: true, isCustom: false, license: 'OFL', characterSupport: 'Latin', languageSupport: ['TR', 'EN', 'DE'] },
  { id: 'font_lexend', name: 'Lexend', family: 'Lexend, sans-serif', weights: ['100', '300', '400', '500', '600', '700', '800', '900'], styles: ['normal'], isMonospace: false, isFavorite: false, isInstalled: true, isEnabled: true, isCustom: false, license: 'OFL', characterSupport: 'Latin', languageSupport: ['TR', 'EN'] },
  { id: 'font_general_sans', name: 'General Sans', family: '"General Sans", sans-serif', weights: ['300', '400', '500', '600', '700'], styles: ['normal', 'italic'], isMonospace: false, isFavorite: true, isInstalled: true, isEnabled: true, isCustom: false, license: 'Proprietary Indian Type Foundry', characterSupport: 'Latin', languageSupport: ['EN', 'FR', 'DE'] },
  { id: 'font_cabinet_grotesk', name: 'Cabinet Grotesk', family: '"Cabinet Grotesk", sans-serif', weights: ['100', '200', '300', '400', '500', '600', '700', '800', '900'], styles: ['normal'], isMonospace: false, isFavorite: false, isInstalled: true, isEnabled: true, isCustom: false, license: 'OFL', characterSupport: 'Latin', languageSupport: ['TR', 'EN'] },
  { id: 'font_urbanist', name: 'Urbanist', family: 'Urbanist, sans-serif', weights: ['100', '200', '300', '400', '500', '600', '700', '800', '900'], styles: ['normal', 'italic'], isMonospace: false, isFavorite: false, isInstalled: true, isEnabled: true, isCustom: false, license: 'OFL', characterSupport: 'Latin', languageSupport: ['TR', 'EN'] },
  { id: 'font_satoshi', name: 'Satoshi', family: 'Satoshi, sans-serif', weights: ['300', '400', '500', '600', '700', '900'], styles: ['normal', 'italic'], isMonospace: false, isFavorite: true, isInstalled: true, isEnabled: true, isCustom: false, license: 'ITF', characterSupport: 'Latin', languageSupport: ['EN', 'DE', 'FR'] },
  { id: 'font_noto_sans', name: 'Noto Sans', family: '"Noto Sans", sans-serif', weights: ['100', '200', '300', '400', '500', '600', '700', '800', '900'], styles: ['normal', 'italic'], isMonospace: false, isFavorite: false, isInstalled: true, isEnabled: true, isCustom: false, license: 'OFL', characterSupport: 'Latin, Multilingual', languageSupport: ['TR', 'EN', 'JP', 'KR', 'ZH'] },
  
  // Monospace Fonts
  { id: 'font_jetbrains', name: 'JetBrains Mono', family: '"JetBrains Mono", monospace', weights: ['100', '200', '300', '400', '500', '600', '700', '800'], styles: ['normal', 'italic'], isMonospace: true, isFavorite: true, isInstalled: true, isEnabled: true, isCustom: false, license: 'OFL', characterSupport: 'Latin, Cyrillic', languageSupport: ['TR', 'EN', 'RU'] },
  { id: 'font_fira_code', name: 'Fira Code', family: '"Fira Code", monospace', weights: ['300', '400', '500', '600', '700'], styles: ['normal'], isMonospace: true, isFavorite: true, isInstalled: true, isEnabled: true, isCustom: false, license: 'OFL', characterSupport: 'Latin, Greek', languageSupport: ['TR', 'EN', 'EL'] },
  { id: 'font_ibm_mono', name: 'IBM Plex Mono', family: '"IBM Plex Mono", monospace', weights: ['100', '200', '300', '400', '500', '600', '700'], styles: ['normal', 'italic'], isMonospace: true, isFavorite: false, isInstalled: true, isEnabled: true, isCustom: false, license: 'OFL', characterSupport: 'Latin, Cyrillic', languageSupport: ['TR', 'EN', 'RU'] },
  { id: 'font_cascadia', name: 'Cascadia Code', family: '"Cascadia Code", monospace', weights: ['300', '400', '600', '700'], styles: ['normal', 'italic'], isMonospace: true, isFavorite: false, isInstalled: true, isEnabled: true, isCustom: false, license: 'OFL', characterSupport: 'Latin', languageSupport: ['TR', 'EN'] },
  { id: 'font_geist_mono', name: 'Geist Mono', family: '"Geist Mono", monospace', weights: ['100', '200', '300', '400', '500', '600', '700', '800', '900'], styles: ['normal'], isMonospace: true, isFavorite: true, isInstalled: true, isEnabled: true, isCustom: false, license: 'OFL', characterSupport: 'Latin', languageSupport: ['TR', 'EN', 'DE'] }
];

// Initialize all fonts with their default typography trees
BUILT_IN_FONTS.forEach(font => {
  font.typographyTree = getDefaultTypographyTree(font.family);
});

export const BUILT_IN_PALETTES: ColorPalette[] = [
  {
    id: 'pal_material',
    name: 'Material Design',
    description: 'Google modern Material You color theory system with deep pastel accents.',
    category: 'Material Design',
    tags: ['Google', 'Modern', 'Adaptive'],
    creationDate: '2026-08-06',
    version: '3.1',
    isFavorite: true,
    isCustom: false,
    primary: '#6750a4',
    secondary: '#625b71',
    accent: '#7d5260',
    background: '#1c1b1f',
    surface: '#2b2930',
    card: '#313033',
    sidebar: '#1c1b1f',
    header: '#211f26',
    border: '#49454f',
    textPrimary: '#e6e1e5',
    textSecondary: '#cac4d0',
    success: '#388e3c',
    warning: '#fbc02d',
    danger: '#f44336',
    info: '#0288d1',
    chartColors: ['#6750a4', '#625b71', '#7d5260', '#0288d1', '#388e3c'],
    glowColors: ['#6750a4', '#7d5260'],
    shadowColors: ['rgba(103, 80, 164, 0.2)']
  },
  {
    id: 'pal_fluent',
    name: 'Fluent UI',
    description: 'Microsoft Fluent design system acrylic corporate colors.',
    category: 'Fluent UI',
    tags: ['Microsoft', 'Windows', 'Corporate'],
    creationDate: '2026-08-06',
    version: '2.0',
    isFavorite: false,
    isCustom: false,
    primary: '#0078d4',
    secondary: '#505050',
    accent: '#0078d4',
    background: '#1f1f1f',
    surface: '#292929',
    card: '#323130',
    sidebar: '#252525',
    header: '#1f1f1f',
    border: '#3b3a39',
    textPrimary: '#ffffff',
    textSecondary: '#a19f9d',
    success: '#107c41',
    warning: '#ffb900',
    danger: '#a80000',
    info: '#0078d4',
    chartColors: ['#0078d4', '#00b7c3', '#0078d4', '#ff8c00', '#107c41'],
    glowColors: ['#0078d4', '#00b7c3'],
    shadowColors: ['rgba(0, 120, 212, 0.25)']
  },
  {
    id: 'pal_apple',
    name: 'Apple Human Interface',
    description: 'Sleek premium visual design language from Cupertino.',
    category: 'Apple Human Interface',
    tags: ['macOS', 'Premium', 'Minimal'],
    creationDate: '2026-08-06',
    version: '15.0',
    isFavorite: true,
    isCustom: false,
    primary: '#007aff',
    secondary: '#8e8e93',
    accent: '#ff2d55',
    background: '#0a0a0c',
    surface: '#16161a',
    card: '#1c1c1e',
    sidebar: '#111115',
    header: '#0f0f13',
    border: '#2c2c2e',
    textPrimary: '#ffffff',
    textSecondary: '#ebebf5',
    success: '#34c759',
    warning: '#ff9500',
    danger: '#ff3b30',
    info: '#5ac8fa',
    chartColors: ['#007aff', '#ff2d55', '#34c759', '#ff9500', '#af52de'],
    glowColors: ['#007aff', '#ff2d55'],
    shadowColors: ['rgba(0, 0, 0, 0.5)']
  },
  {
    id: 'pal_tailwind',
    name: 'Tailwind Default',
    description: 'The beloved standard visual suite of developers everywhere.',
    category: 'Tailwind',
    tags: ['TailwindCSS', 'Standard', 'Clean'],
    creationDate: '2026-08-06',
    version: '4.0',
    isFavorite: true,
    isCustom: false,
    primary: '#3b82f6',
    secondary: '#64748b',
    accent: '#f43f5e',
    background: '#0f172a',
    surface: '#1e293b',
    card: '#1e293b',
    sidebar: '#0f172a',
    header: '#1e293b',
    border: '#334155',
    textPrimary: '#f8fafc',
    textSecondary: '#94a3b8',
    success: '#22c55e',
    warning: '#eab308',
    danger: '#ef4444',
    info: '#06b6d4',
    chartColors: ['#3b82f6', '#f43f5e', '#22c55e', '#eab308', '#06b6d4'],
    glowColors: ['#3b82f6', '#f43f5e'],
    shadowColors: ['rgba(59, 130, 246, 0.2)']
  },
  {
    id: 'pal_shadcn',
    name: 'Shadcn Dark',
    description: 'Sophisticated modern zinc palette styled like shadcn ui.',
    category: 'Shadcn',
    tags: ['Radix', 'Zinc', 'Minimalist'],
    creationDate: '2026-08-06',
    version: '1.2',
    isFavorite: true,
    isCustom: false,
    primary: '#fafafa',
    secondary: '#a1a1aa',
    accent: '#27272a',
    background: '#09090b',
    surface: '#09090b',
    card: '#09090b',
    sidebar: '#09090b',
    header: '#09090b',
    border: '#27272a',
    textPrimary: '#fafafa',
    textSecondary: '#a1a1aa',
    success: '#10b981',
    warning: '#f59e0b',
    danger: '#ef4444',
    info: '#3b82f6',
    chartColors: ['#fafafa', '#a1a1aa', '#27272a', '#3b82f6', '#ef4444'],
    glowColors: ['#fafafa', '#a1a1aa'],
    shadowColors: ['rgba(255, 255, 255, 0.05)']
  },
  {
    id: 'pal_nord',
    name: 'Nord Studio',
    description: 'Arctic visual palette with muted blue-grey tones.',
    category: 'Nord',
    tags: ['Nordic', 'Ice', 'Cozy'],
    creationDate: '2026-08-06',
    version: '1.0',
    isFavorite: false,
    isCustom: false,
    primary: '#88c0d0',
    secondary: '#81a1c1',
    accent: '#b48ead',
    background: '#2e3440',
    surface: '#3b4252',
    card: '#434c5e',
    sidebar: '#2e3440',
    header: '#3b4252',
    border: '#4c566a',
    textPrimary: '#eceff4',
    textSecondary: '#d8dee9',
    success: '#a3be8c',
    warning: '#ebcb8b',
    danger: '#bf616a',
    info: '#8fbcbb',
    chartColors: ['#88c0d0', '#81a1c1', '#b48ead', '#a3be8c', '#8fbcbb'],
    glowColors: ['#88c0d0', '#8fbcbb'],
    shadowColors: ['rgba(136, 192, 208, 0.15)']
  },
  {
    id: 'pal_catppuccin',
    name: 'Catppuccin Mocha',
    description: 'Soothing pastel colors for hackers who love aesthetics.',
    category: 'Catppuccin',
    tags: ['Mocha', 'Flavour', 'Cute'],
    creationDate: '2026-08-06',
    version: '1.4',
    isFavorite: true,
    isCustom: false,
    primary: '#cba6f7',
    secondary: '#89b4fa',
    accent: '#f5c2e7',
    background: '#1e1e2e',
    surface: '#252538',
    card: '#313244',
    sidebar: '#11111b',
    header: '#181825',
    border: '#45475a',
    textPrimary: '#cdd6f4',
    textSecondary: '#bac2de',
    success: '#a6e3a1',
    warning: '#f9e2af',
    danger: '#f38ba8',
    info: '#74c7ec',
    chartColors: ['#cba6f7', '#89b4fa', '#f5c2e7', '#a6e3a1', '#74c7ec'],
    glowColors: ['#cba6f7', '#f5c2e7'],
    shadowColors: ['rgba(203, 166, 247, 0.2)']
  },
  {
    id: 'pal_tokyo',
    name: 'Tokyo Night',
    description: 'Dark, cold neon lights of Shinjuku at midnight.',
    category: 'Tokyo Night',
    tags: ['Tokyo', 'Neon', 'Vapor'],
    creationDate: '2026-08-06',
    version: '2.1',
    isFavorite: true,
    isCustom: false,
    primary: '#7aa2f7',
    secondary: '#565f89',
    accent: '#bb9af3',
    background: '#1a1b26',
    surface: '#24283b',
    card: '#2f354f',
    sidebar: '#16161e',
    header: '#1f2335',
    border: '#383e5a',
    textPrimary: '#a9b1d6',
    textSecondary: '#787c99',
    success: '#9ece6a',
    warning: '#e0af68',
    danger: '#f7768e',
    info: '#0db9d7',
    chartColors: ['#7aa2f7', '#bb9af3', '#9ece6a', '#e0af68', '#f7768e'],
    glowColors: ['#7aa2f7', '#bb9af3'],
    shadowColors: ['rgba(122, 162, 247, 0.2)']
  },
  {
    id: 'pal_gruvbox',
    name: 'Gruvbox Retro',
    description: 'Retro warm design with a classic typewriter and paper aura.',
    category: 'Gruvbox',
    tags: ['Warm', 'Vintage', 'Muted'],
    creationDate: '2026-08-06',
    version: '1.1',
    isFavorite: false,
    isCustom: false,
    primary: '#fabd2f',
    secondary: '#83a598',
    accent: '#fe8019',
    background: '#282828',
    surface: '#3c3836',
    card: '#504945',
    sidebar: '#1d2021',
    header: '#32302f',
    border: '#665c54',
    textPrimary: '#fbf1c7',
    textSecondary: '#bdae93',
    success: '#b8bb26',
    warning: '#fabd2f',
    danger: '#fb4934',
    info: '#83a598',
    chartColors: ['#fabd2f', '#83a598', '#fe8019', '#b8bb26', '#fb4934'],
    glowColors: ['#fabd2f', '#fe8019'],
    shadowColors: ['rgba(250, 189, 47, 0.1)']
  },
  {
    id: 'pal_dracula',
    name: 'Dracula Gothic',
    description: 'Classic rich vampire colors loved by developers worldwide.',
    category: 'Dracula',
    tags: ['Gothic', 'Vampire', 'Classic'],
    creationDate: '2026-08-06',
    version: '1.0',
    isFavorite: true,
    isCustom: false,
    primary: '#bd93f9',
    secondary: '#6272a4',
    accent: '#ff79c6',
    background: '#282a36',
    surface: '#343746',
    card: '#44475a',
    sidebar: '#1e1f29',
    header: '#21222c',
    border: '#6272a4',
    textPrimary: '#f8f8f2',
    textSecondary: '#6272a4',
    success: '#50fa7b',
    warning: '#f1fa8c',
    danger: '#ff5555',
    info: '#8be9fd',
    chartColors: ['#bd93f9', '#ff79c6', '#8be9fd', '#50fa7b', '#f1fa8c'],
    glowColors: ['#bd93f9', '#ff79c6'],
    shadowColors: ['rgba(189, 147, 249, 0.3)']
  },
  {
    id: 'pal_cyberpunk',
    name: 'Cyberpunk 2077',
    description: 'High tech, low life. Bright aggressive yellow and deep cyan.',
    category: 'Cyberpunk',
    tags: ['Aggressive', 'Neon', 'Rebel'],
    creationDate: '2026-08-06',
    version: '4.0',
    isFavorite: true,
    isCustom: false,
    primary: '#f3e600',
    secondary: '#00f0ff',
    accent: '#ff0055',
    background: '#040508',
    surface: '#0d0f17',
    card: '#161924',
    sidebar: '#07080c',
    header: '#0d0f17',
    border: '#ff0055',
    textPrimary: '#00f0ff',
    textSecondary: '#a3a6b8',
    success: '#39ff14',
    warning: '#f3e600',
    danger: '#ff0055',
    info: '#00f0ff',
    chartColors: ['#f3e600', '#00f0ff', '#ff0055', '#39ff14', '#af40ff'],
    glowColors: ['#ff0055', '#00f0ff'],
    shadowColors: ['rgba(255, 0, 85, 0.4)']
  },
  {
    id: 'pal_neon',
    name: 'Acid Neon Vapor',
    description: 'Glow-focused visual style with intense radioactive tones.',
    category: 'Neon',
    tags: ['Glow', 'Club', 'Rave'],
    creationDate: '2026-08-06',
    version: '3.0',
    isFavorite: false,
    isCustom: false,
    primary: '#39ff14',
    secondary: '#ff007f',
    accent: '#7f00ff',
    background: '#0a0014',
    surface: '#140024',
    card: '#1e0033',
    sidebar: '#05000a',
    header: '#140024',
    border: '#ff007f',
    textPrimary: '#ffffff',
    textSecondary: '#b8a3cc',
    success: '#39ff14',
    warning: '#ffff00',
    danger: '#ff0000',
    info: '#00ffff',
    chartColors: ['#39ff14', '#ff007f', '#7f00ff', '#00ffff', '#ffff00'],
    glowColors: ['#39ff14', '#ff007f'],
    shadowColors: ['rgba(57, 255, 20, 0.3)']
  },
  {
    id: 'pal_glass',
    name: 'Aero Glass Crystal',
    description: 'Translucent pristine white look that emphasizes blur.',
    category: 'Glass',
    tags: ['Aero', 'Premium', 'Pristine'],
    creationDate: '2026-08-06',
    version: '5.2',
    isFavorite: true,
    isCustom: false,
    primary: '#ffffff',
    secondary: '#cbd5e1',
    accent: '#38bdf8',
    background: '#090d16',
    surface: 'rgba(255, 255, 255, 0.08)',
    card: 'rgba(255, 255, 255, 0.12)',
    sidebar: 'rgba(255, 255, 255, 0.05)',
    header: 'rgba(255, 255, 255, 0.09)',
    border: 'rgba(255, 255, 255, 0.2)',
    textPrimary: '#f8fafc',
    textSecondary: '#cbd5e1',
    success: '#10b981',
    warning: '#f59e0b',
    danger: '#ef4444',
    info: '#06b6d4',
    chartColors: ['#ffffff', '#cbd5e1', '#38bdf8', '#06b6d4', '#10b981'],
    glowColors: ['rgba(255,255,255,0.4)', '#38bdf8'],
    shadowColors: ['rgba(0, 0, 0, 0.2)']
  },
  {
    id: 'pal_luxury',
    name: 'Royale Luxury',
    description: 'Gold dust and obsidian marble for luxury dashboards.',
    category: 'Luxury',
    tags: ['Gold', 'Black', 'Executive'],
    creationDate: '2026-08-06',
    version: '1.0',
    isFavorite: true,
    isCustom: false,
    primary: '#d4af37',
    secondary: '#aa7c11',
    accent: '#aa7c11',
    background: '#070708',
    surface: '#121214',
    card: '#1b1b1f',
    sidebar: '#0d0d0f',
    header: '#121214',
    border: '#d4af37',
    textPrimary: '#ffffff',
    textSecondary: '#d4af37',
    success: '#2e7d32',
    warning: '#f57f17',
    danger: '#c62828',
    info: '#1565c0',
    chartColors: ['#d4af37', '#aa7c11', '#121214', '#1565c0', '#2e7d32'],
    glowColors: ['#d4af37', '#aa7c11'],
    shadowColors: ['rgba(212, 175, 55, 0.2)']
  },
  {
    id: 'pal_amoled',
    name: 'Ultra AMOLED Black',
    description: 'Pure pitch black background (#000) for ultimate battery saver.',
    category: 'AMOLED',
    tags: ['PitchBlack', 'OLED', 'BatterySaver'],
    creationDate: '2026-08-06',
    version: '2.0',
    isFavorite: true,
    isCustom: false,
    primary: '#ffffff',
    secondary: '#71717a',
    accent: '#3f3f46',
    background: '#000000',
    surface: '#09090b',
    card: '#121214',
    sidebar: '#000000',
    header: '#09090b',
    border: '#27272a',
    textPrimary: '#fafafa',
    textSecondary: '#a1a1aa',
    success: '#10b981',
    warning: '#f59e0b',
    danger: '#ef4444',
    info: '#3b82f6',
    chartColors: ['#ffffff', '#71717a', '#3f3f46', '#10b981', '#ef4444'],
    glowColors: ['#ffffff', '#27272a'],
    shadowColors: ['rgba(0, 0, 0, 0)']
  }
];

// Helper to check which assets are recommended by AI
export function getAIAssetRecommendations(
  wallpaperDominantColor: string,
  wallpaperIsDark: boolean,
  currentPresetId?: string
): AIRecommendation {
  // Let's create an intelligent selector based on actual wallpaper tones
  let recommendedPaletteId = 'pal_tailwind';
  let recommendedFontId = 'font_inter';
  let reason = '';
  let compScore = 98;
  let readScore = 95;
  let contrastScore = 96;
  let visualHarmony = 97;

  const hex = wallpaperDominantColor.toLowerCase();

  // Red/Pink/Cyan cyber tones
  if (hex.includes('ff00') || hex.includes('3b82') || hex.includes('0a0') || currentPresetId?.includes('cyber')) {
    recommendedPaletteId = 'pal_cyberpunk';
    recommendedFontId = 'font_geist';
    reason = "Duvar kağıdı dinamik siber tonlar ve yüksek doygunlukta neonlar içeriyor. 'Cyberpunk 2077' paleti en canlı kontrastı sağlarken, 'Geist Sans' fütüristik çizgileriyle okunabilirliği zirveye çıkarır.";
    compScore = 99;
  } 
  // Green aurora tones
  else if (hex.includes('10b9') || hex.includes('06e') || currentPresetId?.includes('aurora')) {
    recommendedPaletteId = 'pal_catppuccin';
    recommendedFontId = 'font_plus_jakarta';
    reason = "Kuzey ışıkları yeşili ve pastel teal tonları taranmıştır. 'Catppuccin Mocha' konforlu pastel dokunuşlarla gözü yormaz. 'Plus Jakarta Sans' ile mükemmel harf uyumu yakalanır.";
    compScore = 97;
  }
  // Dracula purple tones
  else if (hex.includes('bd93') || hex.includes('purp') || hex.includes('a855')) {
    recommendedPaletteId = 'pal_dracula';
    recommendedFontId = 'font_space_grotesk';
    reason = "Duvar kağıdında asil mor ve lila geçişleri tespit edildi. 'Dracula Gothic' paleti zengin kontrastı korurken, 'Space Grotesk' monoline geometrisiyle modern bir hava katar.";
    compScore = 98;
  }
  // Muted/Cozy blue grey tones
  else if (hex.includes('88c0') || hex.includes('nord') || hex.includes('slate')) {
    recommendedPaletteId = 'pal_nord';
    recommendedFontId = 'font_inter';
    reason = "Soğuk buğulu cam atmosferi algılandı. 'Nord Studio' soğuk gri zeminler üzerinde dengeli kontrast sunar. 'Inter' gövde metinlerinde maksimum okunabilirlik sağlar.";
    compScore = 96;
  }
  // Otherwise default dark sleek
  else {
    recommendedPaletteId = 'pal_tokyo';
    recommendedFontId = 'font_outfit';
    reason = "Gece yarısı gökyüzü pikselleri ve derin karanlık tonlar analiz edildi. Tokyo Night Shinjuku neon estetiğini yansıtırken, 'Outfit' sans-serif kavisleriyle arayüze premium bir yumuşaklık kazandırır.";
    compScore = 95;
    readScore = 96;
    contrastScore = 94;
  }

  return {
    recommendedPaletteId,
    recommendedFontId,
    compatibilityScore: compScore,
    readabilityScore: readScore,
    contrastScore: contrastScore,
    visualHarmonyScore: visualHarmony,
    reason
  };
}
