import {
  LiquidGlassConfig,
  ModuleConfig,
  NavigationPreferences,
  SidebarProfile,
} from '../types/navigation';

export const GLASS_PRESETS: Record<string, LiquidGlassConfig> = {
  minimal: {
    preset: 'minimal',
    blur: 20,
    opacity: 70,
    saturation: 120,
    brightness: 100,
    noise: 0,
    borderWidth: 1,
    borderOpacity: 28,
    borderRadius: 16,
    shadowDepth: 'subtle',
    elevation: 2,
    quality: 'balanced',
    lightResponse: 'subtle',
    adaptiveContrast: true,
  },
  clear: {
    preset: 'clear',
    blur: 8,
    opacity: 30,
    saturation: 140,
    brightness: 108,
    noise: 0,
    borderWidth: 1.5,
    borderOpacity: 40,
    borderRadius: 16,
    shadowDepth: 'subtle',
    elevation: 1,
    quality: 'quality',
    lightResponse: 'standard',
    adaptiveContrast: true,
  },
  deep: {
    preset: 'deep',
    blur: 32,
    opacity: 85,
    saturation: 110,
    brightness: 95,
    noise: 4,
    borderWidth: 1.5,
    borderOpacity: 32,
    borderRadius: 18,
    shadowDepth: 'deep',
    elevation: 4,
    quality: 'ultra',
    lightResponse: 'subtle',
    adaptiveContrast: true,
  },
  frosted: {
    preset: 'frosted',
    blur: 48,
    opacity: 90,
    saturation: 130,
    brightness: 98,
    noise: 6,
    borderWidth: 1.5,
    borderOpacity: 45,
    borderRadius: 20,
    shadowDepth: 'medium',
    elevation: 3,
    quality: 'ultra',
    lightResponse: 'subtle',
    adaptiveContrast: true,
  },
  'ultra-thin': {
    preset: 'ultra-thin',
    blur: 4,
    opacity: 15,
    saturation: 150,
    brightness: 112,
    noise: 0,
    borderWidth: 1.5,
    borderOpacity: 50,
    borderRadius: 14,
    shadowDepth: 'subtle',
    elevation: 1,
    quality: 'performance',
    lightResponse: 'standard',
    adaptiveContrast: true,
  },
  thin: {
    preset: 'thin',
    blur: 12,
    opacity: 45,
    saturation: 125,
    brightness: 105,
    noise: 0,
    borderWidth: 1,
    borderOpacity: 25,
    borderRadius: 16,
    shadowDepth: 'subtle',
    elevation: 1,
    quality: 'balanced',
    lightResponse: 'subtle',
    adaptiveContrast: true,
  },
  regular: {
    preset: 'regular',
    blur: 24,
    opacity: 75,
    saturation: 115,
    brightness: 100,
    noise: 2,
    borderWidth: 1,
    borderOpacity: 30,
    borderRadius: 18,
    shadowDepth: 'medium',
    elevation: 2,
    quality: 'balanced',
    lightResponse: 'subtle',
    adaptiveContrast: true,
  },
  thick: {
    preset: 'thick',
    blur: 40,
    opacity: 88,
    saturation: 110,
    brightness: 95,
    noise: 4,
    borderWidth: 2,
    borderOpacity: 40,
    borderRadius: 20,
    shadowDepth: 'deep',
    elevation: 4,
    quality: 'quality',
    lightResponse: 'subtle',
    adaptiveContrast: true,
  },
  'ultra-thick': {
    preset: 'ultra-thick',
    blur: 56,
    opacity: 96,
    saturation: 105,
    brightness: 90,
    noise: 8,
    borderWidth: 2.5,
    borderOpacity: 55,
    borderRadius: 24,
    shadowDepth: 'deep',
    elevation: 5,
    quality: 'ultra',
    lightResponse: 'off',
    adaptiveContrast: true,
  },
  custom: {
    preset: 'custom',
    blur: 24,
    opacity: 75,
    saturation: 120,
    brightness: 100,
    noise: 2,
    borderWidth: 1.5,
    borderOpacity: 30,
    borderRadius: 16,
    shadowDepth: 'subtle',
    elevation: 2,
    quality: 'balanced',
    lightResponse: 'subtle',
    adaptiveContrast: true,
  },
};

export const INITIAL_MODULES: Record<string, ModuleConfig> = {
  mainmenu: {
    id: 'mainmenu',
    title: 'Ana Menü',
    shortName: 'ANA MENÜ',
    iconName: 'Home',
    color: '#3b82f6',
    visible: true,
    enabled: true,
    pinned: true,
    order: 0,
    securityLevel: 'none',
    subPages: [
      {
        id: 'overview-dashboard',
        moduleId: 'mainmenu',
        label: 'Sistem Genel Bakış',
        iconName: 'LayoutDashboard',
        isFavorite: true,
        visible: true,
        enabled: true,
        order: 0,
        securityLevel: 'none',
        description: 'Sistem özeti, metrikler ve ana göstergeler',
      },
      {
        id: 'overview-workspace',
        moduleId: 'mainmenu',
        label: 'Çalışma Alanı',
        iconName: 'Layers',
        isFavorite: true,
        visible: true,
        enabled: true,
        order: 1,
        securityLevel: 'none',
        description: 'Aktif modül çalışma alanı tuvali',
      },
      {
        id: 'fav-quick-access',
        moduleId: 'mainmenu',
        label: 'Favori Sayfalarım',
        iconName: 'Star',
        isFavorite: true,
        visible: true,
        enabled: true,
        order: 2,
        securityLevel: 'none',
        description: 'Hızlı erişim için sabitlenmiş sayfalar',
      },
      {
        id: 'recent-history',
        moduleId: 'mainmenu',
        label: 'Son Kullanılanlar',
        iconName: 'Clock',
        isFavorite: false,
        visible: true,
        enabled: true,
        order: 3,
        securityLevel: 'none',
        description: 'En son ziyaret edilen sayfaların geçmişi',
      },
    ],
  },
  personelos: {
    id: 'personelos',
    title: 'PersonelOs',
    shortName: 'PERSONELOS',
    iconName: 'UserCheck',
    color: '#6366f1',
    badge: 'IK',
    visible: true,
    enabled: true,
    pinned: false,
    order: 1,
    securityLevel: 'none',
    subPages: [
      {
        id: 'personelos-main',
        moduleId: 'personelos',
        label: 'Personel Yönetimi',
        iconName: 'UserCheck',
        isFavorite: false,
        visible: true,
        enabled: true,
        order: 0,
        securityLevel: 'none',
        description: 'Çalışan listesi, profiller ve birimler',
      },
      {
        id: 'personelos-shifts',
        moduleId: 'personelos',
        label: 'İzin & Vardiya Takibi',
        iconName: 'CalendarDays',
        isFavorite: false,
        visible: true,
        enabled: true,
        order: 1,
        securityLevel: 'none',
        description: 'Vardiya çizelgeleri ve yıllık izin onayları',
      },
      {
        id: 'personelos-payroll',
        moduleId: 'personelos',
        label: 'Bordro & Özlük Hakları',
        iconName: 'CreditCard',
        isFavorite: false,
        visible: true,
        enabled: true,
        order: 2,
        securityLevel: 'protected',
        description: 'Maaş ödemeleri ve personel özlük dosyaları',
      },
      {
        id: 'personelos-performance',
        moduleId: 'personelos',
        label: 'Performans & Hedefler',
        iconName: 'TrendingUp',
        isFavorite: false,
        visible: true,
        enabled: true,
        order: 3,
        securityLevel: 'none',
        description: 'Dönemsel KPI ve hedef değerlendirmeleri',
      },
    ],
  },
  workos: {
    id: 'workos',
    title: 'WorkOs',
    shortName: 'WORKOS',
    iconName: 'Briefcase',
    color: '#0284c7',
    badge: 5,
    visible: true,
    enabled: true,
    pinned: true,
    order: 2,
    securityLevel: 'none',
    subPages: [
      {
        id: 'workos-main',
        moduleId: 'workos',
        label: 'İş & Proje Alanı',
        iconName: 'Briefcase',
        isFavorite: true,
        visible: true,
        enabled: true,
        order: 0,
        securityLevel: 'none',
        description: 'Aktif kurumsal projeler ve genel durum',
      },
      {
        id: 'workos-kanban',
        moduleId: 'workos',
        label: 'Kanban & Görev Panosu',
        iconName: 'CheckSquare',
        isFavorite: false,
        visible: true,
        enabled: true,
        order: 1,
        securityLevel: 'none',
        description: 'Sürükle-bırak görev akışları ve sprintler',
      },
      {
        id: 'workos-timetrack',
        moduleId: 'workos',
        label: 'Zaman & Efor Takibi',
        iconName: 'Clock',
        isFavorite: false,
        visible: true,
        enabled: true,
        order: 2,
        securityLevel: 'none',
        description: 'Görev başına harcanan süre ve log kayıtları',
      },
      {
        id: 'workos-reports',
        moduleId: 'workos',
        label: 'Proje Raporları',
        iconName: 'FileBarChart',
        isFavorite: false,
        visible: true,
        enabled: true,
        order: 3,
        securityLevel: 'none',
        description: 'Tamamlanma oranları ve hız metrikleri',
      },
    ],
  },
  mediaos: {
    id: 'mediaos',
    title: 'MediaOs',
    shortName: 'MEDIAOS',
    iconName: 'Tv',
    color: '#f43f5e',
    visible: true,
    enabled: true,
    pinned: false,
    order: 3,
    securityLevel: 'none',
    subPages: [
      {
        id: 'mediaos-main',
        moduleId: 'mediaos',
        label: 'Medya Merkezi',
        iconName: 'Tv',
        isFavorite: false,
        visible: true,
        enabled: true,
        order: 0,
        securityLevel: 'none',
        description: 'Video akışları, yayınlar ve galeri',
      },
      {
        id: 'mediaos-live',
        moduleId: 'mediaos',
        label: 'Canlı Akış & Yayıncı',
        iconName: 'Radio',
        isFavorite: false,
        visible: true,
        enabled: true,
        order: 1,
        securityLevel: 'none',
        description: 'Canlı video yayını ve kamera girişleri',
      },
      {
        id: 'mediaos-audio',
        moduleId: 'mediaos',
        label: 'Ses & Podcast Kütüphanesi',
        iconName: 'Headphones',
        isFavorite: false,
        visible: true,
        enabled: true,
        order: 2,
        securityLevel: 'none',
        description: 'Kayıtlar, podcast serileri ve ortam müzikleri',
      },
    ],
  },
  libraryos: {
    id: 'libraryos',
    title: 'LibraryOs',
    shortName: 'LIBRARYOS',
    iconName: 'Library',
    color: '#d97706',
    visible: true,
    enabled: true,
    pinned: false,
    order: 4,
    securityLevel: 'none',
    subPages: [
      {
        id: 'libraryos-main',
        moduleId: 'libraryos',
        label: 'Kütüphane Yönetimi',
        iconName: 'Library',
        isFavorite: false,
        visible: true,
        enabled: true,
        order: 0,
        securityLevel: 'none',
        description: 'Kitaplar, makaleler ve e-arşiv',
      },
      {
        id: 'libraryos-docs',
        moduleId: 'libraryos',
        label: 'Dokümantasyon & Wiki',
        iconName: 'BookOpen',
        isFavorite: false,
        visible: true,
        enabled: true,
        order: 1,
        securityLevel: 'none',
        description: 'Şirket içi bilgi bankası ve kılavuzlar',
      },
      {
        id: 'libraryos-notes',
        moduleId: 'libraryos',
        label: 'Notlar & Defterler',
        iconName: 'NotebookPen',
        isFavorite: false,
        visible: true,
        enabled: true,
        order: 2,
        securityLevel: 'none',
        description: 'Markdown notları ve kişisel arşiv',
      },
    ],
  },
  intelligeos: {
    id: 'intelligeos',
    title: 'IntelligeOs',
    shortName: 'INTELLIGEOS',
    iconName: 'BrainCircuit',
    color: '#9333ea',
    badge: 'AI',
    visible: true,
    enabled: true,
    pinned: true,
    order: 5,
    securityLevel: 'none',
    subPages: [
      {
        id: 'intelligeos-main',
        moduleId: 'intelligeos',
        label: 'Zeka & Model Alanı',
        iconName: 'BrainCircuit',
        isFavorite: true,
        visible: true,
        enabled: true,
        order: 0,
        securityLevel: 'none',
        description: 'Gemini, yerel LLM ve AI ajan modelleri',
      },
      {
        id: 'intelligeos-prompts',
        moduleId: 'intelligeos',
        label: 'İstem / Prompt Stüdyosu',
        iconName: 'Sparkles',
        isFavorite: false,
        visible: true,
        enabled: true,
        order: 1,
        securityLevel: 'none',
        description: 'Özel sistem talimatları ve şablonlar',
      },
      {
        id: 'intelligeos-workflows',
        moduleId: 'intelligeos',
        label: 'Otonom Ajan Akışları',
        iconName: 'Network',
        isFavorite: false,
        visible: true,
        enabled: true,
        order: 2,
        securityLevel: 'none',
        description: 'Çok adımlı otomatik işlem boru hatları',
      },
    ],
  },
  files: {
    id: 'files',
    title: 'Dosya Yöneticisi',
    shortName: 'DOSYALAR',
    iconName: 'FolderKanban',
    color: '#059669',
    visible: true,
    enabled: true,
    pinned: true,
    order: 6,
    securityLevel: 'none',
    subPages: [
      {
        id: 'files-main',
        moduleId: 'files',
        label: 'Tüm Dosyalar & Dokümanlar',
        iconName: 'FolderKanban',
        isFavorite: true,
        visible: true,
        enabled: true,
        order: 0,
        securityLevel: 'none',
        description: 'Toplu dosya listesi, arama ve filtreleme',
      },
      {
        id: 'files-documents',
        moduleId: 'files',
        label: 'PDF & Ofis Belgeleri',
        iconName: 'FileText',
        isFavorite: false,
        visible: true,
        enabled: true,
        order: 1,
        securityLevel: 'none',
        description: 'Resmi evraklar, sözleşmeler ve raporlar',
      },
      {
        id: 'files-storage',
        moduleId: 'files',
        label: 'Depolama Analizi & Arşiv',
        iconName: 'HardDrive',
        isFavorite: false,
        visible: true,
        enabled: true,
        order: 2,
        securityLevel: 'none',
        description: 'Disk kullanım alanı ve yedekleme yönetimi',
      },
    ],
  },
  appstore: {
    id: 'appstore',
    title: 'Açık Kaynak Uygulamalar',
    shortName: 'UYGULAMALAR',
    iconName: 'Boxes',
    color: '#0d9488',
    visible: true,
    enabled: true,
    pinned: false,
    order: 7,
    securityLevel: 'none',
    subPages: [
      {
        id: 'appstore-main',
        moduleId: 'appstore',
        label: 'Uygulama Mağazası & Havuz',
        iconName: 'Boxes',
        isFavorite: false,
        visible: true,
        enabled: true,
        order: 0,
        securityLevel: 'none',
        description: 'Kurulabilir açık kaynak ve topluluk eklentileri',
      },
      {
        id: 'appstore-installed',
        moduleId: 'appstore',
        label: 'Yüklü Uygulamalar',
        iconName: 'Package',
        isFavorite: false,
        visible: true,
        enabled: true,
        order: 1,
        securityLevel: 'none',
        description: 'Aktif modül ve paketlerin konfigürasyonu',
      },
      {
        id: 'appstore-devtools',
        moduleId: 'appstore',
        label: 'Geliştirici Araçları & CLI',
        iconName: 'Terminal',
        isFavorite: false,
        visible: true,
        enabled: true,
        order: 2,
        securityLevel: 'protected',
        description: 'API test araçları, konsol ve eklenti geliştirme',
      },
    ],
  },
};

export const DEFAULT_LAYOUT = {
  primaryWidth: 58,
  secondaryWidth: 248,
  compactWidth: 56,
  gap: 8,
  outerMargin: 0,
  topOffset: 0,
  bottomOffset: 0,
  cornerRadius: 16,
  contentSpacing: 8,
};

export const DEFAULT_AUTOHIDE = {
  enabled: true,
  hideDelay: 3000,
  revealDelay: 100,
  revealZone: 16,
  revealOnHover: true,
  revealOnNavigation: true,
  revealOnKeyboard: true,
  edgeReveal: 'both' as const,
};

export const DEFAULT_INTERACTION = {
  idleCollapseMs: 4000,
  tempExpandOnHover: true,
  hoverDelayMs: 150,
  collapseDelayMs: 250,
  sensitivity: 'normal' as const,
  isLocked: false,
};

export const DEFAULT_APPEARANCE = {
  iconSize: 18,
  showLabels: 'icon-only' as const,
  density: 'comfortable' as const,
  showSearch: true,
  showHeader: true,
  showFooter: true,
  tooltipsEnabled: true,
  tooltipDelay: 200,
};

export const DEFAULT_ANIMATION = {
  enabled: true,
  duration: 'normal' as const,
  customDurationMs: 220,
  reducedMotion: false,
};

export const DEFAULT_SHORTCUTS = {
  togglePrimary: 'Ctrl+B',
  toggleSecondary: 'Ctrl+Shift+B',
  focusMode: 'Ctrl+Shift+F',
  commandPalette: 'Ctrl+K',
};

export const DEFAULT_FOCUS_LIGHT = {
  color: 'cyan' as const,
  customColorHex: '#00E5FF',
  speed: 'normal' as const,
  intensity: 'vivid' as const,
  enabled: true,
};

export const BUILTIN_PROFILES: SidebarProfile[] = [
  {
    id: 'default',
    name: 'Varsayılan ApexOS',
    description: 'Dengeli çift seviyeli şık navigasyon düzeni.',
    iconName: 'LayoutGrid',
    navMode: 'expanded',
    smartnessLevel: 'adaptive',
    position: 'left',
    secondaryPlacement: 'attached',
    layout: { ...DEFAULT_LAYOUT, primaryWidth: 58, secondaryWidth: 248 },
    glassConfig: GLASS_PRESETS.minimal,
    autoHide: DEFAULT_AUTOHIDE,
    interaction: DEFAULT_INTERACTION,
    appearance: DEFAULT_APPEARANCE,
    animation: DEFAULT_ANIMATION,
    activeModules: ['mainmenu', 'personelos', 'workos', 'mediaos', 'libraryos', 'intelligeos', 'files', 'appstore'],
  },
  {
    id: 'work',
    name: 'Work & Productivity',
    description: 'İş, görevler ve dosya yönetimini öne çıkaran kompakt profil.',
    iconName: 'Briefcase',
    navMode: 'compact',
    smartnessLevel: 'intelligent',
    position: 'left',
    secondaryPlacement: 'attached',
    layout: { ...DEFAULT_LAYOUT, primaryWidth: 56, secondaryWidth: 230, compactWidth: 52 },
    glassConfig: GLASS_PRESETS.clear,
    autoHide: DEFAULT_AUTOHIDE,
    interaction: { ...DEFAULT_INTERACTION, idleCollapseMs: 20000 },
    appearance: { ...DEFAULT_APPEARANCE, density: 'compact' },
    animation: DEFAULT_ANIMATION,
    activeModules: ['mainmenu', 'workos', 'personelos', 'files', 'intelligeos'],
  },
  {
    id: 'media',
    name: 'Media & Library',
    description: 'Yayın, kütüphane ve dokümantasyon odaklı geniş profil.',
    iconName: 'Tv',
    navMode: 'expanded',
    smartnessLevel: 'assisted',
    position: 'left',
    secondaryPlacement: 'attached',
    layout: { ...DEFAULT_LAYOUT, primaryWidth: 60, secondaryWidth: 260 },
    glassConfig: GLASS_PRESETS.deep,
    autoHide: DEFAULT_AUTOHIDE,
    interaction: DEFAULT_INTERACTION,
    appearance: { ...DEFAULT_APPEARANCE, density: 'spacious' },
    animation: DEFAULT_ANIMATION,
    activeModules: ['mainmenu', 'mediaos', 'libraryos', 'files'],
  },
  {
    id: 'developer',
    name: 'Developer & AI Studio',
    description: 'Yapay zeka, modüller ve açık kaynak araçları için derin cam profil.',
    iconName: 'Terminal',
    navMode: 'expanded',
    smartnessLevel: 'manual',
    position: 'left',
    secondaryPlacement: 'attached',
    layout: { ...DEFAULT_LAYOUT, primaryWidth: 62, secondaryWidth: 256 },
    glassConfig: GLASS_PRESETS.frosted,
    autoHide: DEFAULT_AUTOHIDE,
    interaction: { ...DEFAULT_INTERACTION, isLocked: true },
    appearance: { ...DEFAULT_APPEARANCE, density: 'comfortable' },
    animation: DEFAULT_ANIMATION,
    activeModules: ['mainmenu', 'intelligeos', 'appstore', 'files', 'workos'],
  },
  {
    id: 'focus',
    name: 'Ultra Focus',
    description: 'Tüm menüleri gizleyerek içerik alanına maksimum odaklanma sağlar.',
    iconName: 'Maximize2',
    navMode: 'focus',
    smartnessLevel: 'adaptive',
    position: 'left',
    secondaryPlacement: 'attached',
    layout: { ...DEFAULT_LAYOUT, primaryWidth: 54, secondaryWidth: 220 },
    glassConfig: GLASS_PRESETS.minimal,
    autoHide: { ...DEFAULT_AUTOHIDE, hideDelay: 1000 },
    interaction: DEFAULT_INTERACTION,
    appearance: DEFAULT_APPEARANCE,
    animation: DEFAULT_ANIMATION,
    activeModules: ['mainmenu', 'workos', 'intelligeos', 'files'],
  },
];

export const DEFAULT_PREFERENCES: NavigationPreferences = {
  version: 2,
  applyMode: 'live',
  activeProfileId: 'default',
  navMode: 'expanded',
  smartnessLevel: 'adaptive',
  position: 'left',
  secondaryPlacement: 'attached',
  layout: DEFAULT_LAYOUT,
  autoHide: DEFAULT_AUTOHIDE,
  interaction: DEFAULT_INTERACTION,
  appearance: DEFAULT_APPEARANCE,
  animation: DEFAULT_ANIMATION,
  shortcuts: DEFAULT_SHORTCUTS,
  glassConfig: GLASS_PRESETS.minimal,
  focusLightConfig: DEFAULT_FOCUS_LIGHT,
  modules: INITIAL_MODULES,
  moduleOrder: ['mainmenu', 'personelos', 'workos', 'mediaos', 'libraryos', 'intelligeos', 'files', 'appstore'],
  securityPin: '1234',
  customProfiles: [],
  recentPages: ['overview-dashboard', 'workos-main', 'files-main'],
  favoritePages: ['overview-dashboard', 'overview-workspace', 'fav-quick-access', 'workos-main', 'intelligeos-main', 'files-main'],
  moduleUsageStats: {
    mainmenu: 24,
    workos: 18,
    files: 15,
    intelligeos: 12,
    personelos: 5,
    libraryos: 4,
    mediaos: 3,
    appstore: 2,
  },
  minimumContentWidth: 640,
  
  // Backward compatibility getters
  s1Width: 58,
  s2Width: 248,
  autoHideIdleMs: 4000,
  tempExpandOnHover: true,
};

